---
title: "D2SC ICMA Notebook"
output: html_notebook
author: "Maanav Choudhary"
date: "`r Sys.Date()`"
---

# ICMA Sept 9 2024

```{r}
plot(cars)
```

```{r}
ohno_this_is_a_nightmare <- "hello"
```


```{r}
2+2
```

```{r}
x <- 2+2
```
Value gets saved in environment
```{r}
?mean
```

```{r}
mean(c(1,2,3))
```
```{r}
mean(my_vector)
```

```{r}
my_vector <- c(2,3,4)
```

```{r}
?sd
sd(1:2) ^2
```

```{r}
my_numbers <- c(1,2,3,4,5,6,7,8,9,10)
getwd()
```

```{r}
my_numbers %>%
  mean()
```


# ICMA Sept 23 2024
 #pivot_longer(): requires data and the columns you want to pivot into long form

```{r}
library(tidyverse)
```
```{r}
head(billboard)
billboard_long <- billboard %>%
  pivot_longer(cols = starts_with("wk"),names_to = "week",names_prefix= "wk", values_to = "position",values_drop_na= TRUE)
billboard_long
```
```{r}
billboard_long %>%
  pivot_wider(names_from= week, values_from =position)
```

```{r}
billboard_sep <-billboard %>%
  separate(col = date.entered,into =c("year","month","day") ,sep = "-")
```

```{r}
billboard_sep %>%
  unite(col = "full date", c(year,month,day))

```


